/**
 * IMAGE v2.0 — AI Image Generator + Image Tools
 * !img / !image / !gambar / !lukis — Generate gambar AI
 * !imgstyle — Generate dengan style khusus
 * !imgvariasi — Variasi prompt cerdas
 */
const axios = require('axios');

const IMAGE_STYLES = {
    anime:      'anime style, Studio Ghibli inspired, vibrant colors, detailed',
    realistic:  'photorealistic, DSLR photo, 8k uhd, hyper detailed',
    cartoon:    'cartoon style, Disney/Pixar inspired, colorful, fun',
    painting:   'oil painting, masterpiece, museum quality, detailed brushwork',
    sketch:     'pencil sketch, detailed linework, artistic, black and white',
    watercolor: 'watercolor painting, soft colors, artistic, flowing',
    cyberpunk:  'cyberpunk style, neon lights, futuristic, dark atmosphere',
    fantasy:    'epic fantasy art, magical, mystical, dramatic lighting',
    minimal:    'minimalist design, clean, simple, flat illustration',
    vintage:    'vintage retro style, 1950s aesthetic, warm tones, nostalgic'
};

const NEGATIVE_PROMPT = 'nsfw, nude, explicit, blurry, low quality, bad anatomy, deformed, ugly, watermark, text, logo';

module.exports = async (command, args, msg, user, db, sock) => {
    const valid = ['img','image','gambar','lukis','imgstyle','imgvariasi','imghelp'];
    if (!valid.includes(command)) return;

    const jid = msg.key?.remoteJid || msg.from;

    // ── HELP ──────────────────────────────────────────────────
    if (command === 'imghelp') {
        const styleList = Object.keys(IMAGE_STYLES).map((s,i) => `${i+1}. \`${s}\``).join(' | ');
        return msg.reply(
            `🎨 *AI IMAGE GENERATOR — BANTUAN*\n\n` +
            `*Perintah:*\n` +
            `🖼️ \`!img <deskripsi>\` — Generate gambar\n` +
            `🎨 \`!imgstyle <style> <deskripsi>\` — Generate dengan style\n` +
            `🔀 \`!imgvariasi <deskripsi>\` — 3 variasi berbeda\n\n` +
            `*Style tersedia:*\n${styleList}\n\n` +
            `*Tips prompt bagus:*\n` +
            `• Gunakan bahasa Inggris\n` +
            `• Tambahkan detail (warna, pencahayaan, suasana)\n` +
            `• Sebutkan gaya artistik\n\n` +
            `*Contoh:*\n` +
            `\`!img sunset over futuristic Tokyo city, golden hour, epic\`\n` +
            `\`!imgstyle anime girl with white hair in cherry blossom garden\``
        );
    }

    // ── STYLE GENERATOR ────────────────────────────────────────
    if (command === 'imgstyle') {
        const styleKey = args[0]?.toLowerCase();
        if (!styleKey || !IMAGE_STYLES[styleKey]) {
            const list = Object.keys(IMAGE_STYLES).map(k => `\`${k}\``).join(', ');
            return msg.reply(`🎨 *IMAGE STYLE GENERATOR*\n\nFormat: \`!imgstyle <style> <deskripsi>\`\n\nStyle: ${list}\n\nContoh: \`!imgstyle anime wanita samurai di bawah pohon sakura\``);
        }
        const prompt = args.slice(1).join(' ');
        if (!prompt) return msg.reply('❌ Masukkan deskripsi gambar!\n\nContoh: `!imgstyle cyberpunk motorcycle rider in Tokyo rain`');

        await sock.sendMessage(jid, { react: { text: '🎨', key: msg.key } });
        await msg.reply(`🎨 *Generating ${styleKey} image...*\nSabar ya, AI lagi melukis! ✏️`);

        const enhancedPrompt = `${prompt}, ${IMAGE_STYLES[styleKey]}, high quality, masterpiece`;
        const encoded = encodeURIComponent(enhancedPrompt);
        const negEncoded = encodeURIComponent(NEGATIVE_PROMPT);
        const imageUrl = `https://image.pollinations.ai/prompt/${encoded}?nologo=true&negative=${negEncoded}&width=1024&height=1024`;

        try {
            await sock.sendMessage(jid, {
                image: { url: imageUrl },
                caption: `🎨 *AI Art — Style: ${styleKey.toUpperCase()}*\n\nPrompt: _"${prompt}"_\n\n_Generated by Algojo AI 🤖_`
            }, { quoted: msg });
            await sock.sendMessage(jid, { react: { text: '✅', key: msg.key } });
        } catch(e) {
            await sock.sendMessage(jid, { react: { text: '❌', key: msg.key } });
            await msg.reply('❌ Gagal generate gambar. Coba lagi dengan prompt berbeda!');
        }
        return;
    }

    // ── VARIASI GENERATOR ──────────────────────────────────────
    if (command === 'imgvariasi') {
        const prompt = args.join(' ');
        if (!prompt) return msg.reply('🔀 *IMAGE VARIASI*\n\nFormat: `!imgvariasi <deskripsi>`\n\nGenerate 3 gambar dengan variasi berbeda dari prompt yang sama.');

        await sock.sendMessage(jid, { react: { text: '🔀', key: msg.key } });
        await msg.reply('🔀 *Generating 3 variasi gambar...*\nIni agak lama ya, tunggu sebentar! 🎨');

        const variations = [
            { suffix: 'daytime, bright lighting, vibrant colors', seed: Math.floor(Math.random()*99999) },
            { suffix: 'nighttime, dramatic lighting, moody atmosphere', seed: Math.floor(Math.random()*99999) },
            { suffix: 'golden hour, cinematic, epic composition', seed: Math.floor(Math.random()*99999) }
        ];

        let successCount = 0;
        for (let i = 0; i < variations.length; i++) {
            const v = variations[i];
            const enhPrompt = `${prompt}, ${v.suffix}, high quality, masterpiece, detailed`;
            const encoded = encodeURIComponent(enhPrompt);
            const imageUrl = `https://image.pollinations.ai/prompt/${encoded}?nologo=true&seed=${v.seed}`;
            try {
                await sock.sendMessage(jid, {
                    image: { url: imageUrl },
                    caption: `🔀 *Variasi ${i+1}/3*\nPrompt: "${prompt}" + ${v.suffix}`
                }, { quoted: msg });
                successCount++;
                await new Promise(r => setTimeout(r, 1000));
            } catch(e) { console.error(`Variasi ${i+1} gagal:`, e.message); }
        }

        if (successCount > 0) {
            await sock.sendMessage(jid, { react: { text: '✅', key: msg.key } });
            await msg.reply(`✅ *${successCount}/3 variasi berhasil dibuat!*`);
        } else {
            await sock.sendMessage(jid, { react: { text: '❌', key: msg.key } });
            await msg.reply('❌ Semua variasi gagal. Server AI mungkin sibuk, coba lagi nanti.');
        }
        return;
    }

    // ── STANDARD IMAGE GENERATOR ──────────────────────────────
    const prompt = args.join(' ');
    if (!prompt) {
        return msg.reply(
            `🎨 *AI IMAGE GENERATOR*\n\n` +
            `Format: \`!img <deskripsi gambar>\`\n\n` +
            `Perintah lain:\n` +
            `🎨 \`!imgstyle\` — Generate dengan style khusus\n` +
            `🔀 \`!imgvariasi\` — 3 variasi berbeda\n` +
            `❓ \`!imghelp\` — Bantuan lengkap\n\n` +
            `Contoh:\n` +
            `\`!img sunset di pantai bali dengan perahu nelayan\`\n` +
            `\`!img cat wearing sunglasses on a motorbike, anime style\``
        );
    }

    await sock.sendMessage(jid, { react: { text: '🎨', key: msg.key } });
    await msg.reply('🎨 *AI sedang melukis...* Tunggu sebentar ya! ✏️');

    const enhancedPrompt = `${prompt}, high quality, detailed, 4k, masterpiece`;
    const encoded = encodeURIComponent(enhancedPrompt);
    const negEncoded = encodeURIComponent(NEGATIVE_PROMPT);
    const imageUrl = `https://image.pollinations.ai/prompt/${encoded}?nologo=true&negative=${negEncoded}`;

    try {
        await sock.sendMessage(jid, {
            image: { url: imageUrl },
            caption: `🎨 *AI Art by Algojo*\n\nPrompt: _"${prompt}"_\n\n_Tips: \`!imgstyle\` untuk style khusus_`
        }, { quoted: msg });
        await sock.sendMessage(jid, { react: { text: '✅', key: msg.key } });
    } catch(e) {
        await sock.sendMessage(jid, { react: { text: '❌', key: msg.key } });
        let errMsg = '❌ Gagal generate gambar.';
        if (e.message?.includes('timeout') || e.message?.includes('network')) errMsg += ' Server AI sibuk, coba lagi nanti.';
        else errMsg += ' Coba ganti prompt dengan kata-kata lebih sederhana (bahasa Inggris lebih baik).';
        await msg.reply(errMsg);
    }
};
